apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app-deployment
  labels:
    app: simple-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app-container
        image: simple-flask-app:latest
        ports:
        - containerPort: 5000
