apiVersion: v1
kind: Service
metadata:
  name: simple-flask-app-service
spec:
  selector:
    app: simple-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
