name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t meeramohan323/simpleflaskapp:${{ github.sha }} .
        docker push meeramohan323/simpleflaskapp:${{ github.sha }}

    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.K8S_SERVER }}
        username: ${{ secrets.K8S_USER }}
        key: ${{ secrets.K8S_SSH_KEY }}
        script: |
          kubectl set image deployment/simple-flask-app-deployment simple-flask-app-container=<YOUR_DOCKER_USERNAME>/simpleflaskapp:${{ github.sha }}
